"""Export model_bundle.json in a form the web app can consume.

The web app runs from file:// (just open checkin-app.html), so it
can't fetch() local JSON. This script emits two files:

  model_bundle.js     — `window.MODEL_BUNDLE = {...}`. Drop this in
                        the same folder as the HTML and add a
                        <script src="model_bundle.js"></script> before
                        the React app, and the model auto-loads.
  model_bundle.b64    — same payload, base64-encoded text. Easier to
                        copy-paste into the web app's "Import model"
                        textarea on a phone.

The web app accepts both forms.
"""

from __future__ import annotations
import argparse
import base64
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
DEFAULT_BUNDLE = OUT / "model_bundle.json"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", default=str(DEFAULT_BUNDLE),
                    help="path to model_bundle.json")
    ap.add_argument("--out-dir", default=str(OUT.parent),
                    help="where to drop model_bundle.js / .b64 "
                         "(default: project root, next to checkin-app.html)")
    args = ap.parse_args()

    src = Path(args.bundle)
    if not src.exists():
        raise SystemExit(f"{src} not found. Run train.py first.")
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    payload = json.loads(src.read_text())
    # Strip the bulky `metrics` block — the web app doesn't need it and
    # it inflates the file by ~10x.
    payload.pop("metrics", None)
    compact = json.dumps(payload, separators=(",", ":"))

    js_path = out_dir / "model_bundle.js"
    js_path.write_text(
        "/* auto-generated by bundle_to_js.py — do not edit by hand */\n"
        "window.MODEL_BUNDLE = " + compact + ";\n"
    )

    b64_path = out_dir / "model_bundle.b64"
    b64_path.write_text(base64.b64encode(compact.encode("utf-8")).decode("ascii"))

    size_kb = len(compact) / 1024
    print(f"Wrote {js_path}  ({size_kb:.1f} KB)")
    print(f"Wrote {b64_path}  (paste into 'Import model' in the web app)")
    print()
    print("To use in the web app:")
    print(f"  Either:  open checkin-app.html (model_bundle.js auto-loads)")
    print(f"  Or:      menu -> Import model -> paste contents of model_bundle.b64")


if __name__ == "__main__":
    main()
